// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username,
  hashedpassword,
  fullname,
  email

) VALUES (
  $1, $2, $3, $4
) RETURNING username, hashedpassword, fullname, email, password_changed_at, created_at
`

type CreateUserParams struct {
	Username       string `json:"username"`
	Hashedpassword string `json:"hashedpassword"`
	Fullname       string `json:"fullname"`
	Email          string `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Hashedpassword,
		arg.Fullname,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.Username,
		&i.Hashedpassword,
		&i.Fullname,
		&i.Email,
		&i.PasswordChangedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT username, hashedpassword, fullname, email, password_changed_at, created_at FROM users
WHERE  username = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, username)
	var i User
	err := row.Scan(
		&i.Username,
		&i.Hashedpassword,
		&i.Fullname,
		&i.Email,
		&i.PasswordChangedAt,
		&i.CreatedAt,
	)
	return i, err
}
