apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-bank-api-deployment
  labels:
    app: simple-bank-api
spec:
  replicas:  1
  selector:
    matchLabels:
      app: simple-bank-api
  template:
    metadata:
      labels:
        app: simple-bank-api
    spec:
      containers:
      - name: simple-bank-api
        image: 252380158032.dkr.ecr.us-east-1.amazonaws.com/simplebank:19a06282a8cb6ecc950baa674dca991c7cdb130a
        ports:
        - containerPort: 8080
