apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-bank-api-deployment
  labels:
    app: simple-bank-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-bank-api
  template:
    metadata:
      labels:
        app: simple-bank-api
    spec:
      containers:
      - name: simple-bank-api
        image: 252380158032.dkr.ecr.us-east-1.amazonaws.com/simplebank:9a460e5e4cdbedcf1f58ff4e810111a0caae0462
        ports:
        - containerPort: 8080
        env:
          - name: DB_URL
            value: "postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"