name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Install golang-migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.0/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate /usr/local/bin/migrate

    - name: Run migrations
      env:
        # Makefile uses DB_URL
        DB_URL: postgresql://root:secret@localhost:5432/simple_bank?sslmode=disable
      run: make migrateup 
    
    - name: Test
      env:
        # Your Go code (config.go) looks for DB_URL
        DB_URL: postgresql://root:secret@localhost:5432/simple_bank?sslmode=disable
        DB_DRIVER: postgres
      run: make test