name: Deploy to Production

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Install golang-migrate
        run: make install-migrate

      - name: Run Migrations
        env:
          DB_URL: postgresql://root:secret@localhost:5432/simple_bank?sslmode=disable
        run: |
          $(go env GOPATH)/bin/migrate -path db/migration -database "$DB_URL" -verbose up

      - name: Run Test
        env:
          DB_SOURCE: postgresql://root:secret@localhost:5432/simple_bank?sslmode=disable
        run: make test   #go test -v -cover ./... || true 

  deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::252380158032:role/github-action-role
          aws-region: us-east-1

      - name: Login to Amazon ECR 
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Load secrets and save to app.env
        run: |
          aws secretsmanager get-secret-value \
            --secret-id simple_bank \
            --query SecretString \
            --output text | jq -r 'to_entries | .[] | "\(.key)=\(.value)"' > app.env
            
      - name: Verify app.env is not empty
        run: |
          if [ ! -s app.env ]; then
            echo "The app.env file is empty. Failing build."
            exit 1
          fi    

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: simplebank
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest